sudo: required
services:
  - docker

#before_install:
#  - docker build -t opan/udemy -f ./client/Dockerfile.dev ./client
#
#script:
#  - docker run opan/udemy npm test -- --coverage
#
#after_success:
#  - docker build -t opan/udemy-client ./client
#  - docker build -t opan/udemy-nginx ./nginx
#  - docker build -t opan/udemy-server ./server
#  - docker build -t opan/udemy-worker ./worker
#  # Log in to Docker hub
#  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
#  # Take those images and push them to Docker hub
#  - docker push opan/udemy-client
#  - docker push opan/udemy-nginx
#  - docker push opan/udemy-server
#  - docker push opan/udemy-worker